### ISSUE TITLE
shellout on windows may fail when non ASCII chars are in the path

### ISSUE THREAD

**Issue by mwrock** [chef/mixlib-shellout#117]
see https://github.com/chef-cookbooks/windows/issues/332 where a resource fails and a shell out is involved and a non ascii characher (like ü) is in the path. It is raising:
```
Encoding::CompatibilityError: windows_package[Ruby 2.1.7-p400] (windev::packages line 24) had an error: Encoding::CompatibilityError: incompatible character encodings: IBM437 and ASCII-8BIT
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.3-universal-mingw32/lib/mixlib/shellout/windows/core_ext.rb:132:in `join'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.3-universal-mingw32/lib/mixlib/shellout/windows/core_ext.rb:132:in `create'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.3-universal-mingw32/lib/mixlib/shellout/windows.rb:80:in `run_command'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.3-universal-mingw32/lib/mixlib/shellout.rb:259:in `run_command'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/mixin/shell_out.rb:97:in `shell_out_command'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/mixin/shell_out.rb:50:in `shell_out'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/mixin/shell_out.rb:55:in `shell_out!'
l:/scripts/local-mode-cache/cache/cookbooks/windows/libraries/windows_package.rb:102:in `install_package'
l:/scripts/local-mode-cache/cache/cookbooks/windows/libraries/windows_package.rb:29:in `block in <class:WindowsCookbookPackage>'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/provider/lwrp_base.rb:86:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/provider/lwrp_base.rb:86:in `block in action'
```

**Comment by mwrock** [comment]
closing this here. its final home is in chef core: https://github.com/chef/chef/pull/4626
