### ISSUE TITLE
Doesn't take array form on windows

### ISSUE THREAD

**Issue by zenspider** [chef/mixlib-shellout#180]
```
PS C:\Users\vagrant\Desktop> irb -rmixlib/shellout
irb(main):001:0> Mixlib::ShellOut.new(*%w[echo hello world]).run_command
Traceback (most recent call last):
        8: from C:/opscode/chefdk/embedded/bin/irb.cmd:31:in `<main>'
        7: from C:/opscode/chefdk/embedded/bin/irb.cmd:31:in `load'
        6: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        5: from (irb):1
        4: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4-universal-mingw32/lib/mixlib/shellout.rb:267:in `run_command'
        3: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4-universal-mingw32/lib/mixlib/shellout/windows.rb:69:in `run_command'
        2: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4-universal-mingw32/lib/mixlib/shellout/windows.rb:200:in `command_to_run'
        1: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4-universal-mingw32/lib/mixlib/shellout/windows.rb:269:in `should_run_under_cmd?'
NoMethodError (undefined method `each_char' for ["echo", "hello", "world"]:Array)
Did you mean?  each_cons
```

**Comment by lamont-granquist** [comment]
dup of #125
