### ISSUE TITLE
Running a command with non-string array element raises "TypeError: no implicit conversion from nil to integer"

### ISSUE THREAD

**Issue by roman-yepishev-enoc** [chef/mixlib-shellout#90]
STR with chef-12.0.3:

1. chef-apply -e 'execute "blah" do command ["/bin/true", 0] end' -l debug

Expected results:
"/bin/true 0" is executed

Actual results:
```
[2015-02-05T10:04:21-05:00] DEBUG: TypeError: execute[blah] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: TypeError: no implicit conversion from nil to integer
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout/unix.rb:337:in `kill'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout/unix.rb:337:in `reap_errant_child'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout/unix.rb:97:in `ensure in run_command'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout/unix.rb:105:in `run_command'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:237:in `run_command'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:91:in `shell_out_command'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:44:in `shell_out'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:49:in `shell_out!'
/opt/chef/embedded/apps/chef/lib/chef/provider/execute.rb:60:in `block in action_run'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/execute.rb:59:in `action_run'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/application/apply.rb:150:in `run_chef_recipe'
/opt/chef/embedded/apps/chef/lib/chef/application/apply.rb:159:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application/apply.rb:172:in `run'
/opt/chef/embedded/apps/chef/bin/chef-apply:25:in `<top (required)>'
/usr/bin/chef-apply:40:in `load'
/usr/bin/chef-apply:40:in `<main>'

```

**Comment by lamont-granquist** [comment]
Ruby's exec doesn't use a null-terminated string like C.  This works:

```
chef-apply -e 'execute "blah" do command ["/usr/bin/true"] end' -l debug
```

As does this:

```
chef-apply -e 'execute "blah" do command ["/bin/echo", "foo"] end' -l debug
```

**Comment by roman-yepishev-enoc** [comment]
I don't see how null-terminated string is relevant.

Also reproducible with:
```
chef-apply -e 'execute "blah" do command ["ping", "-c", 5, "127.0.0.1"] end' -l debug
```

**Comment by lamont-granquist** [comment]
The bare '5' is the issue, this works:

```
chef-apply -e 'execute "blah" do command ["ping", "-c", "5", "127.0.0.1"] end' -l debug
```

**Comment by roman-yepishev-enoc** [comment]
Yes, that **is** the bug. `shellout` accepts input that makes it crash with no way of knowing it was caused by the argument list.

Either it needs to reject the command right away or it should stringify the arguments so that the error does not happen.

**Comment by copumpkin** [comment]
I'm getting the same error but am not passing in raw numbers. Looks like "no implicit conversion from nil to integer" is just one of the things you get if you screw something up (still trying to find the cause of mine)
